version: "2.3"
services:
  proxy:
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: always
  go-ex:
    build: .
    restart: always
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exchange_db
      MYSQL_ROOT_PASSWORD: 3nYzRaLtpM4
    command:
      ["--character-set-server=utf8", "--collation-server=utf8_general_ci"]
    restart: always
  pma:
    image: nazarpc/phpmyadmin
    ports:
      - 8080:80
    environment:
      UPLOAD_SIZE: 1G
      MYSQL_HOST: db
    restart: always
volumes:
  mysql-data:
    driver: local